name: workspace
channels:
  - anaconda
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - jupyterlab
  - ipython
  - matplotlib
  - numpy
  - scipy
  - pandas
  - pytorch-cpu
  - torchvision-cpu
  - pip
  - swig
  - pip:
    - tensorboard==2.2  # current jupyter-tensorboard has error with standard_tensorboard_wsgi
    - networkx
    - lightning-bolts
    - tensorboardX
    - jupyter-tensorboard
    - crc32c # for tensorboardX
