name: workspace
channels:
  - anaconda
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - ipython
  - jupyterlab
  - matplotlib
  - numpy
  - scipy
  - pandas
  - pytorch-cpu
  - torchvision-cpu
  - pip
  - swig
  - pip:
    - tensorflow
    - networkx
    - lightning-bolts[extra]
    - tensorboardX
    - crc32c # for tensorboardX
