name: workspace
channels:
  - defaults
  - conda-forge
  - pytorch
  - pyg
dependencies:
  - python=3.8
  - jupyterlab
  - ipython
  - matplotlib
  - numpy
  - scipy
  - pandas
  - pytorch=1.9.1
  - torchvision
  - torchaudio
  - cpuonly
  - pyg
  - pip
  - swig
  - pip:
    - networkx
    - pytorch-lightning
    - lightning-bolts
    - tensorboardX
    - jupyter-tensorboard
    - crc32c # for tensorboardX
